---
title: "BoleteRa Crosstalk"
author: "Xavier de Pedro"
date: "15 d’octubre de 2017"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r install and load required packages if needed, echo=FALSE}
if (!require("devtools")) install.packages("devtools"); require(devtools)

# Packages for Data manipulation
if (!require("readODS")) install.packages("readODS"); library(readODS)
if (!require("readxl")) install.packages("readxl"); library(readxl)
if (!require("dplyr")) install.packages("dplyr"); library(dplyr)

# Packages for Html5 Output manipulation
# Add package widget frame so that we attempt to get responsive iframes produced by htmlwidgets
# See: https://github.com/bhaskarvk/widgetframe
if(!require(widgetframe)){ install.packages("widgetframe") }; require(widgetframe)
if(!require(htmlwidgets)){ install.packages("htmlwidgets") }; require(htmlwidgets) 
# Add webshot to allow making screenshots from htmlwidgets for printed versions of reports
if(!require(webshot)){ install.packages("webshot") }; require(webshot)
# Install also phantomjs thorugh webshot as a required dependency (only once)
#webshot::install_phantomjs(baseURL = "https://bitbucket.org/ariya/phantomjs/downloads/")

# Packages for Maps
if (!require("tmap")) install.packages("tmap")
if (!require("leaflet")) install_github("rstudio/leaflet"); library(leaflet)
if (!require("leaflet.minicharts")) install.packages("leaflet.minicharts"); library(leaflet.minicharts)

# Packages for Interactive Tables
if (!require("DT")) install.packages("DT"); library(DT)
if (!require(rpivotTable)){ install.packages("rpivotTable") }; require(rpivotTable)

# Packages for Dashboard-like UI to display results 
# See https://rstudio.github.io/crosstalk/using.html
if (!require("crosstalk")) install_github("rstudio/crosstalk"); library(crosstalk)
# Test adding an easy interface to allow changing htmlwidget on the go with manipulatewidget
# See: https://github.com/rte-antares-rpackage/manipulateWidget
if (!require("manipulateWidget")) install.packages("manipulateWidget"); library(manipulateWidget) 

```

## Read source data

```{r Read data, echo=FALSE}
  # =======================================================
  # Use readODS package to keep data easily in a Visual Spreadsheet in LibreOffice
  # =======================================================
  # 
  # Code will come here

# Define some paths
htmlpath <- "html"

#read_ods(path = NULL, sheet = 1, col_names = TRUE, col_types = NULL, na = "", skip = 0, formula_as_formula = FALSE, range = NULL)
#read_ods("table.ods", header = TRUE) ## return only the first sheet
#read_ods("multisheet.ods", sheet = 2, formula_as_formula = TRUE) ## return the second sheet with formula read as formula

```

## Thematic map

See: https://github.com/mtennekes/tmap

```{r Thematic map, echo=FALSE}
  # =======================================================
  # Use the thematic maps package
  # See: https://github.com/mtennekes/tmap
  # =======================================================
  # 
  # Code will come here


```

## Crosstalk with filters

Taken from https://rstudio.github.io/crosstalk/using.html

```{r Crosstalk with filters, echo=FALSE}
### Dataset
#read datasets
require(readr)
data.dir  <- "~/Sync/BQa5_Zamiadroid/Citations/"
#data.file <- "20140000_20170900_bolets_Zamia_TAB_Xavier_dePedro.csv"
data.file <- "20140000_20171014_bolets_Zamia_TAB.csv"
d <- readr::read_csv(paste0(data.dir, data.file), col_names = TRUE, col_types = NULL,
  na = c("", "NA"), quoted_na = TRUE,
  quote = "\"", comment = "", trim_ws = TRUE, skip = 0, n_max = Inf)

#shared_mtcars <- SharedData$new(mtcars)
#shared_quakes <- SharedData$new(quakes[sample(nrow(quakes), 100),])
#head(quakes)
#head(mtcars)

library(stringr)
#str_split_fixed(d$CitationCoordinates, " ", 2)
d2 <- cbind(d, data.frame(str_split_fixed(d$CitationCoordinates, " ", 2)))
#head(d2)
#str(d2)
names(d2)[ncol(d2)-1] <-  "Latitude"
names(d2)[ncol(d2)] <-  "Longitude"
#str(d2)
d2$Latitude <- as.numeric(levels(d2$Latitude))[d2$Latitude]
d2$Longitude <- as.numeric(levels(d2$Longitude))[d2$Longitude]
d <- d2

# Clean up data and fix oddities for R
d$Date <- strptime(d$Date, "%Y-%m-%d %H:%M:%S")
#d$Pendent[is.na(d$Pendent)] <- "99"
d$Abundància <- gsub("[^0-9]", "", d$Abundància) 
d$Abundància <- as.numeric(d$Abundància)
d$Pendent <- gsub("[^0-9]", "", d$Pendent) 
d$Pendent <- as.numeric(d$Pendent)
d$`nom vulgar (comestible)` <- as.factor(d$`nom vulgar (comestible)`)
d$`nom vulgar (no comestible)` <- as.factor(d$`nom vulgar (no comestible)`)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
# ct stands for CrossTalk
ct.map.table.all <- bscols(
  leaflet::leaflet(d) %>% addTiles() %>% addMarkers(),
  datatable(d[5:9],  filter = 'top', extensions="Scroller", 
            style="bootstrap", class="compact",
            width="100%", rownames = FALSE, 
            options=list(deferRender=TRUE, 
                         scrollY=300, 
                         scroller=TRUE, 
                         pageLength = 5)) %>%
    formatDate('Date', 'toLocaleDateString') %>%
    formatStyle('Abundància', 
                color = styleInterval(c(3, 5), c('black', 'red', 'blue')),
                backgroundColor = styleInterval(c(3, 5), c('white', 'lightyellow', 'yellow'))
              )
)

saveWidget(ct.map.table.all, file=file.path(getwd(), htmlpath, "ct.map.table.all.html"), selfcontained=TRUE) 

ct.map.table.all

```


